language: node_js

node_js:
 sm-deps
  - 0.12
  - iojs
  - 4

before_install:
  - chmod +x gradlew
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: rameshuser123@gmail.com
  password: Tango@123
  organization: SaganCore
  space: Sagan_Core
  on:
    branch: master
notifications:
  webhooks:
     urls:
    - https://github.com/rameshmaveric/weblogic-deployer-ex.git

  

